/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function SlotMachine(props) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('/Models/SlotMachineAssetDraft1.glb')
    const { actions } = useAnimations(animations, group)
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group name="Cube" position={[0, 1.028, -0.49]}>
                    <mesh
                        name="Cube002"
                        geometry={nodes.Cube002.geometry}
                        material={materials['Material.003']}
                    />
                    <mesh
                        name="Cube002_1"
                        geometry={nodes.Cube002_1.geometry}
                        material={materials['Material.002']}
                    />
                    <mesh
                        name="Cube002_2"
                        geometry={nodes.Cube002_2.geometry}
                        material={materials['Material.006']}
                    />
                    <mesh
                        name="Cube002_3"
                        geometry={nodes.Cube002_3.geometry}
                        material={materials['Material.010']}
                    />
                    <mesh
                        name="Cube002_4"
                        geometry={nodes.Cube002_4.geometry}
                        material={materials['Material.014']}
                    />
                    <mesh
                        name="Cube002_5"
                        geometry={nodes.Cube002_5.geometry}
                        material={materials.Material}
                    />
                    <mesh
                        name="Cube002_6"
                        geometry={nodes.Cube002_6.geometry}
                        material={materials['Material.013']}
                    />
                    <mesh
                        name="Cube002_7"
                        geometry={nodes.Cube002_7.geometry}
                        material={materials['Material.007']}
                    />
                    <mesh
                        name="Cube002_8"
                        geometry={nodes.Cube002_8.geometry}
                        material={materials['Material.012']}
                    />
                    <mesh
                        name="Cube002_9"
                        geometry={nodes.Cube002_9.geometry}
                        material={materials['Material.009']}
                    />
                </group>
                <group name="Empty006" position={[0, 4.776, 0.012]} scale={[0.889, 0.458, 0.458]}>
                    <group
                        name="Cylinder001"
                        position={[-0.661, 0, 0]}
                        rotation={[0, 0, -Math.PI / 2]}
                        scale={[2.181, 1.124, 2.181]}>
                        <mesh
                            name="Cylinder002_1"
                            geometry={nodes.Cylinder002_1.geometry}
                            material={materials['Material.004']}
                        />
                        <mesh
                            name="Cylinder002_2"
                            geometry={nodes.Cylinder002_2.geometry}
                            material={materials['Material.005']}
                        />
                    </group>
                    <group
                        name="Cylinder002"
                        position={[-0.212, 0.016, -0.016]}
                        rotation={[0, 0, -Math.PI / 2]}
                        scale={[2.197, 1.133, 2.197]}>
                        <mesh
                            name="Cylinder002_3"
                            geometry={nodes.Cylinder002_3.geometry}
                            material={materials['Material.004']}
                        />
                        <mesh
                            name="Cylinder002_4"
                            geometry={nodes.Cylinder002_4.geometry}
                            material={materials['Material.005']}
                        />
                    </group>
                    <group
                        name="Cylinder003"
                        position={[0.661, 0, 0]}
                        rotation={[0, 0, -Math.PI / 2]}
                        scale={[2.181, 1.124, 2.181]}>
                        <mesh
                            name="Cylinder002_5"
                            geometry={nodes.Cylinder002_5.geometry}
                            material={materials['Material.004']}
                        />
                        <mesh
                            name="Cylinder002_6"
                            geometry={nodes.Cylinder002_6.geometry}
                            material={materials['Material.005']}
                        />
                    </group>
                    <group
                        name="Cylinder004"
                        position={[0.224, 0.007, -0.007]}
                        rotation={[0, 0, -Math.PI / 2]}
                        scale={[2.188, 1.128, 2.188]}>
                        <mesh
                            name="Cylinder002_7"
                            geometry={nodes.Cylinder002_7.geometry}
                            material={materials['Material.004']}
                        />
                        <mesh
                            name="Cylinder002_8"
                            geometry={nodes.Cylinder002_8.geometry}
                            material={materials['Material.005']}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/SlotMachineAssetDraft1.glb')